#PBS -q regular
#PBS -l mppwidth=3072
#PBS -l walltime=00:60:00

cd $PBS_O_WORKDIR

export MPICH_MAX_THREAD_SAFETY=multiple

aprun -e X10_NTHREADS=2 -S 1 -n 512 ./bin/lulesh2.0 -s 20
aprun -e X10_NTHREADS=2 -S 1 -n 512 ./bin/lulesh2.0 -s 20
aprun -e X10_NTHREADS=2 -S 1 -n 512 ./bin/lulesh2.0 -s 20

aprun -e X10_NTHREADS=4 -S 1 -n 512 ./bin/lulesh2.0 -s 20
aprun -e X10_NTHREADS=4 -S 1 -n 512 ./bin/lulesh2.0 -s 20
aprun -e X10_NTHREADS=4 -S 1 -n 512 ./bin/lulesh2.0 -s 20
