#PBS -q regular
#PBS -l mppwidth=20256
#PBS -l walltime=03:30:00

cd $PBS_O_WORKDIR

aprun -e OMP_NUM_THREADS=5 -S 1 -n 3375 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 3375 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 3375 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 3375 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 3375 -cc numa_node -ss ./lulesh2.0 -s 40
