#PBS -q regular
#PBS -l mppwidth=24576
#PBS -l walltime=04:00:00

cd $PBS_O_WORKDIR

aprun -e OMP_NUM_THREADS=5 -S 1 -n 4096 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 4096 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 4096 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 4096 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 4096 -cc numa_node -ss ./lulesh2.0 -s 40
