#PBS -q regular
#PBS -l mppwidth=16464
#PBS -l walltime=03:00:00

cd $PBS_O_WORKDIR

aprun -e OMP_NUM_THREADS=5 -S 1 -n 2744 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 2744 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 2744 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 2744 -cc numa_node -ss ./lulesh2.0 -s 40
aprun -e OMP_NUM_THREADS=5 -S 1 -n 2744 -cc numa_node -ss ./lulesh2.0 -s 40
